# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run API Tests
        id: run-newman
        uses: 
        with:
          collection: collection.json
          reporters: htmlextra
          environement: https://www.postman.com/flight-participant-8024778/workspace/wild-code-school/environment/19501748-55c54bd6-262a-49f5-b22c-3e3821d7dca6

      - name: Installation de newman
        run: npm install -g newman

      - name: Installation de newman reporter htmlextra
        run: npm install -g newman-reporter-htmlextra